---
name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
          cache-dependency-path: subdir/go.sum
      - name: Install dependencies
        run: go get .
      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
